### ISSUE TITLE
Add a kubernetes Elasticsearch setup as "it does suit very well" now on Kubernetes.

### ISSUE THREAD

**Issue by theobolo** [pelias/kubernetes#40]
Hello guys,

In your documentation you'r saying that Elasticsearch is not really well suited for Kubernetes. I think it was true in the pasts years but now there is a lot of Elasticsearch setups running on Kubernetes, as mine for exemple. 

Since you'r not yet supporting Elasticsearch +v2.4.1 versions, i made a kubernetes deployment setup on AKS with my own Elasticsearch 2.4.1 image and a Client/Master/Data statefulsets setup with PersistentDisks / Replication and everything and ... it works like a charm. 

Would you be interested by a PR to add a ES kubernetes deploy method to your project ?

**Comment by orangejulius** [comment]
Hey @theobolo,
I'm glad to hear Elasticsearch on Kubernetes is working well for you. I've still heard a few reports from people running Elasticsearch at a large scale that it doesn't work well in Kubernetes yet. I hope that this will someday not be the case.

I would be interested in seeing a setup for Elasticsearch in K8S, but honestly in terms of bringing it into this repo, I would probably only consider something like the [elasticsearch-operator](https://github.com/upmc-enterprises/elasticsearch-operator). Elasticsearch and K8S are fundamentally at odds because they both include a lot of logic for managing a cluster of instances, and I think its unlikely a solution that doesn't have the ability to take that into account will be reliable in a production setting.

Let me know what you think.

**Comment by theobolo** [comment]
I agree with you ES 2.4 is not the best ES version for Kubernetes (But for the moment Pelias is not functional with ES5 or ES6, i know that you'r working on it).

I recommend to take a look at the excellent work of Pires : https://github.com/pires/kubernetes-elasticsearch-cluster

I made a working setup for my own use because i'm clearly not using "Standalone nodes" to run ES and only k8s clusters for all my apps. I run the full Pelias project (all components) with a ES 2.4 on Kubernetes and for the moment i didn't find any problem. 

ES is managing the Cluster discovery on k8s automatically, there is no need to complex setups and things, really.

There is my ES custom image repo, made from the work of Pires, to have a 2.4 version working image : 

https://github.com/theobolo/docker-elasticsearch/tree/2.4

With that image you can use these deployment files, and that's it ! You have a Production proof cluster with 2 clients nodes / 2 master nodes / 2 data nodes, high available, persistent and fully Scalable. I also added Anti-Affinity rules to avoid running the same ES component on the same k8s worker node. 

https://github.com/theobolo/pelias-elasticsearch

Deploy it into a `pelias` namespace and that's it. It uses a public image made from the first repo. Take a look and try you'll see that's working very well and that's very easy.

**Comment by orangejulius** [comment]
So it's been some time and I still believe that:

1. In general, Elasticsearch is not well suited for Kubernetes. Kubernetes still has many issues with stateful workloads and the complexity of most of the Elasticsearch operators is pretty daunting
2. Regardless of whether or not Elasticsearch works well for some people in Kubernetes, different Pelias users will have different requirements that require a different Elasticsearch solution

So now, this repository itself does not require or promote any particular way of running Elasticsearch.

All the code that used to live in the `elasticsearch` directory has been moved to https://github.com/pelias/terraform-elasticsearch and https://github.com/pelias/packer-elasticsearch, and the README now lists several options for running Elasticsearch.

If there are other good options, we would love a PR recommending them.
