### ISSUE TITLE
Dashboard display empty values

### ISSUE THREAD

**Issue by jdomag** [pelias/kubernetes#87]
Accessing dashbord service, displays page layout with colorful rectangles, however no values are presented inside. Looks like data can;t be read from pelias index in elasticsearch.

**Comment by orangejulius** [comment]
Hey @jdomag,
Thanks for the report. The dashboard is not very well maintained and is prone to failing if things aren't set up just right, and it also doesn't give very clear error messages.

However, I can think of two main reasons this might happen:

1. Elasticsearch isn't configured properly, in which case I would diagnose it by using the API service to work first
2. The dashboard needs a minute or two for the values to initially populate, as internally, all its scripts run in essentially a cron job

If the API can connect to Elasticsearch just fine and you've waited a while with no results, then file an issue in https://github.com/pelias/dashboard with the output of the dashboard pod logs. The dashboard service is not complicated, so if you are fluent in Ruby, a patch to help fix things would be appreciated, as we likely won't get around to it otherwise.
