### ISSUE TITLE
Add chart as dependency 

### ISSUE THREAD

**Issue by tomwassing** [pelias/kubernetes#96]
How can I add this chart to my requirements.yaml file as a dependency? I am unable to find a repository which contains this chart.

**Comment by orangejulius** [comment]
Hey @tomwassing,
Good question, and to be honest I don't really know. I've found the helm dependency system to be a little strange.

It does look like anyone can publish a chart to basically anything that hosts a static website, such as [GitHub pages](https://helm.sh/docs/developing_charts/#github-pages-example).

I'd recommend you host it yourself so that you have full control over the chart. I think the nature of Pelias and Kubernetes means most people make at least small customizations to this chart. But if people would be interested in a publicly hosted chart, we could set up a canonical version via GitHub pages.

What we do for geocode.earth is actually bypass Helm dependencies completely, and use git submodules pinned to specific revisions. That helps us roll out exactly the configuration we want, when we want.

I'm happy to hear any suggestions on how we could make things better for others using the chart.
